version: '2.2'

networks:
  guacamole-net:

services:

  postgres:
    container_name: postgres
    build:
      context: postgres
      dockerfile: ./Dockerfile
    image: 152986443165.dkr.ecr.us-east-1.amazonaws.com/postgres:latest
#    image: postgres
    restart: unless-stopped
    environment:
#      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: guacamole_user
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - ./postgres/data:/var/lib/postgresql/data:rw
#      - ./guacamole_postgres_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - guacamole-net
 
  guacd:
    container_name: guacd
    build:      
      context: guacd
      dockerfile: ./Dockerfile
    image: 152986443165.dkr.ecr.us-east-1.amazonaws.com/guacd:latest
#    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - guacamole-net
    ports:
      - 4822:4822

  guac:
    container_name: guac
    build:
      context: guac
      dockerfile: ./Dockerfile
    image: 152986443165.dkr.ecr.us-east-1.amazonaws.com/guac:latest
#    image: guacamole/guacamole
    restart: unless-stopped
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: somepassword
      GUACD_HOSTNAME: guacd
    networks:
      - guacamole-net
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - guacd


  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    image: 152986443165.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    networks:
      - guacamole-net
    ports:
      - 80:80

