FROM guacamole/guacamole:latest

ENV   POSTGRES_HOSTNAME=postgres \
      POSTGRES_PORT=5432 \
      POSTGRES_DATABASE=guacamole_db \
      POSTGRES_USER=guacamole_user \
      POSTGRES_PASSWORD=somepassword \
      GUACD_HOSTNAME=guacd

EXPOSE 8080
